# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    install:
      - python --version
      - python -m pip install pipx
      - python -m pipx ensurepath
      - PATH="/home/docs/.local/bin:${PATH}" make install-poetry
      - PATH="/home/docs/.local/bin:${PATH}" make install
    build:
      html:
        - echo "Override default build command for html format"
        - PATH="/home/docs/.local/bin:${PATH}" make docs
        - ls -l ./docs/_build/html/*
        - mkdir --parents $READTHEDOCS_OUTPUT/html/
        - cp --recursive ./docs/_build/html/* $READTHEDOCS_OUTPUT/html/
      epub:
        - echo "Override default build command for epub format"
        - PATH="/home/docs/.local/bin:${PATH}" make docs-epub
        - ls -l ./docs/_build/epub/*
        - mkdir -p $READTHEDOCS_OUTPUT/epub/
        - cp ./docs/_build/epub/eventsourcing.epub $READTHEDOCS_OUTPUT/epub/
      pdf:
        - echo "Override default build command for pdf format"
        - PATH="/home/docs/.local/bin:${PATH}" make docs-pdf
        - ls -l ./docs/_build/latex/*
        - mkdir -p $READTHEDOCS_OUTPUT/pdf/
        - cp ./docs/_build/latex/eventsourcing.pdf $READTHEDOCS_OUTPUT/pdf/
sphinx:
  configuration: docs/conf.py
formats:
    - pdf
    - epub
